# Generated by Django 4.1 on 2023-05-04 02:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='music',
            name='music_genre',
            field=models.IntegerField(choices=[(0, 'Jazz'), (1, 'Classic'), (2, 'Pop')], default=0),
        ),
    ]
